name: Build & Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'

    - name: Enable corepack
      run: corepack enable

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build the package
      run: yarn build

    - name: Publish to NPM
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_NPM_TOKEN }}
