name: Build & Publish

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build the package
      run: yarn build
    
    - name: Publish to NPM
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.APIFY_SERVICE_ACCOUNT_NPM_TOKEN }}